namespace EventScoringSystem.Models;

public class Judge
{
    public int Id { get; set; }
    public int EventId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string PinCode { get; set; } = string.Empty; // Autogenerated 6-digit PIN
}